version: '3'
services:
  web:
    image: fraunhoferiosb/frost-server:2.0
    container_name: frost-server-container
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - plugins.multiDatastream.enable=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database

  database:
    container_name: frost-db-container
    image: postgis/postgis:14-3.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    ports:
      - "5432:5432"
    volumes:
      - postgis_volume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: salaheddine.elfarissi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ChangeMe
      PGADMIN_LISTEN_PORT: 90
    ports:
      - "9090:90"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
    postgis_volume:
    pgadmin-data:
